// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnencfkdsyiwtvktdvzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZW5jZmtkc3lpd3R2a3Rkdnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDUyNDUsImV4cCI6MjA2MjIyMTI0NX0.bTZT_trKHsTACQ8rqir304tH89CsiH-XX7Al0ZyIbLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);